'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthContext from '@/components/AuthContext'
import { ApolloProvider } from '@apollo/client/react'
import { client } from '@/graphql/apollo-client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ApolloProvider client={client}>
    <AuthContext>
    <html lang="en">
      <body className={'bg-gray-500'}>{children}</body>
    </html>
    </AuthContext>
    </ApolloProvider>
  )
}
